server:
  port: 9095
  servlet:
    context-path: /identify_service
    session:
      tracking-modes: cookie
      cookie:
        enabled: false
spring:
  session:
    store-type: none
  profiles:
    active: dev # google || aws || dev
  sql:
    init:
      mode: never
      platform: mysql
  h2:
    console:
      enabled: true
  # devtools:
  #   restart:
  #     enabled: false
  #     log-condition-evaluation-delta: false
  # main:
  #   banner-mode: off
  #   log-startup-info: false
  mail:
    host: ${EMAIL_SERVER_HOST}
    port: ${EMAIL_SERVER_PORT}
    username: ${EMAIL_SERVER_USERNAME}
    password: ${EMAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update # none, update, validate, create, create-drop
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            scope: openid, email, profile
            redirect-uri: "${OAUTH2_REDIRECT_URI}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
cookie:
  secure: false # This should be false for localhost (http) development
  http-only: true
  same-site: Lax # Try changing to "None" for cross-domain requests
  max-age: 604800

logging:
  level:
    root: DEBUG # Global log level
    "[org.springframework]": DEBUG # Spring framework logs
    "[org.springframework.boot]": DEBUG
    "[org.springframework.beans.factory]": DEBUG
    "[org.springframework.security.oauth2]": ERROR
    "[org.springframework.web.cors]": DEBUG

