server:
  port: 9095
  servlet:
    context-path: /identify_service

spring:
  profiles:
    active: dev # This sets the default active profile (can be overridden with environment variables)
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.database.study: INFO # Detailed logs for your application's package
    org.hibernate.SQL: WARN # Show SQL queries
    org.hibernate.type: TRACE # Show SQL parameters
    org.springframework: DEBUG # Spring framework logs
    root: INFO # Global log level


