server:
  port: 9095
  servlet:
    context-path: /identify_service

spring:
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  devtools:
    livereload:
      enabled: true
      port: 35729
    remote:
      secret: mysecret
    restart:
      # Enhanced restart configuration
      additional-exclude: false
      additional-paths:
        - src/main/java
        - target/classes
        - target/generated-sources/annotations
      include:
        project: "/study-.*\\.jar"
        mapstruct: "/mapstruct-.*\\.jar"
        exception: "/AppException-.*\\.jar"
        security: "/JwtTokenFilter-.*\\.jar"
        mapper: "/.*mapper.*\\.jar"
        model: "/.*model.*\\.jar"
        entity: "/.*entity.*\\.jar"
        repository: "/.*repository.*\\.jar"
        service: "/.*service.*\\.jar"
        controller: "/.*controller.*\\.jar"
        configuration: "/.*configuration.*\\.jar"
        dto: "/.*dto.*\\.jar"
        generated: "/.*\\$.*\\.class"

# Additional development-specific settings
logging:
  level:
    root: INFO
    "[org.springframework]": DEBUG
    "[org.springframework.boot]": DEBUG
    "[org.springframework.boot.devtools]": DEBUG
    "[org.springframework.boot.autoconfigure]": DEBUG
    "[org.springframework.boot.devtools.restart]": DEBUG
    "[org.springframework.web]": DEBUG
    "[org.springframework.context]": DEBUG
    "[org.apache.catalina.core]": DEBUG
    "[org.apache.tomcat.util.net]": DEBUG

# Novu notification service configuration
novu:
  api-key: 6ac19261e2693610c6a548c4d8fc4a19

