server:
  port: 8080
  servlet:
    context-path: /identify_service
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/your_database?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com.database.study: error

