server:
  port: 9095
  # address: 0.0.0.0 # Using when database is on cloud
  servlet:
    context-path: /identify_service

spring:
  datasource:
    #url: "jdbc:mysql://localhost:3306/identify_service?useSSL=false&allowPublicKeyRetrieval=true"
    #Step 1: Running with the name RECOVER_YOUR_DATA => the script spring boot will change the name of dataBase to identify_service
    #url: "jdbc:mysql://35.228.131.221:3306/RECOVER_YOUR_DATA?useSSL=false&allowPublicKeyRetrieval=true"
    #Step 2: Running with the name identify_service
    url: "jdbc:mysql://35.228.131.221:3306/identify_service?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: root
  h2:
    console:
      enabled: true
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    "[com.database.study]": info # Detailed logs for your application's package
    "[org.hibernate.SQL]": warn # Show SQL queries
    "[org.hibernate.type]": trace # Show SQL parameters
    "[org.springframework]": info # Spring framework logs
    root: info # Global log level


