server:
  port: 9090
  servlet:
    context-path: /identify_service

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identify_service?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
jwt:
  signerKey: "MeoAjf04Sc9Qiadukeu7IdiCqr4O3eBUibjTNfU+yDjzX0Y3W/pWgH1fN6DtM8izgOg69U6qfdcDncXhKEfzxQ=="

logging:
  level:
    "[com.database.study]": error

