spring:
  datasource:
    url: "jdbc:mysql://35.228.131.221:3306/identify_service?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: root
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  # sql:
  #   init:
  #     mode: always
  # schema-locations: classpath:schema.sql
  # data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO # Global log level
    "[com.database.study]": INFO # Detailed logs for your application's package
    "[org.hibernate.SQL]": WARN # Show SQL queries
    "[org.hibernate.type]": TRACE # Show SQL parameters
    "[org.springframework]": DEBUG # Spring framework logs


