server:
  port: 9095
  servlet:
    context-path: /identify_service
spring:
  profiles:
    active: dev # google || aws || dev
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
      log-condition-evaluation-delta: false
  # main:
  #   banner-mode: off
  #   log-startup-info: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            scope: openid, email, profile
            redirect-uri: "${OAUTH2_REDIRECT_URI}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
logging:
  level:
    root: WARN # Global log level
    "[com.database.study]": WARN # Detailed logs for your application's package
    "[org.springframework.boot.devtools]": WARN
    "[org.hibernate.SQL]": ERROR # Show SQL queries
    "[org.hibernate.type]": ERROR # Show SQL parameters
    "[org.springframework]": ERROR # Spring framework logs
    "[org.springframework.security]": ERROR
    "[org.springframework.security.oauth2]": ERROR

