server:
  port: 9095
  # address: 0.0.0.0
  servlet:
    context-path: /identify_service

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identify_service?useSSL=false&allowPublicKeyRetrieval=true"
    # url: "jdbc:mysql://35.228.131.221:3306/identify_service?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    "[com.database.study]": info # Detailed logs for your application's package
    "[org.hibernate.SQL]": warn # Show SQL queries
    "[org.hibernate.type]": trace # Show SQL parameters
    "[org.springframework]": info # Spring framework logs
    root: info # Global log level


