spring:
  # driver-class-name: com.mysql.cj.jdbc.Driver
  # batch:
  #   jdbc:
  #     initialize-schema: "always"
  h2:
    console:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
logging:
  level:
    root: INFO # Global log level
    "[com.database.study]": INFO # Detailed logs for your application's package
    "[org.hibernate.SQL]": WARN # Show SQL queries
    "[org.hibernate.type]": TRACE # Show SQL parameters
    "[org.springframework]": DEBUG # Spring framework logs


