server:
  port: 9095
  servlet:
    context-path: /identify_service
spring:
  profiles:
    active: dev # prod || dev
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            scope: openid, email, profile
            redirect-uri: "${OAUTH2_REDIRECT_URI}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
logging:
  level:
    root: INFO # Global log level
    "[com.database.study]": INFO # Detailed logs for your application's package
    "[org.hibernate.SQL]": WARN # Show SQL queries
    "[org.hibernate.type]": TRACE # Show SQL parameters
    "[org.springframework]": DEBUG # Spring framework logs
    "[org.springframework.security]": DEBUG
    "[org.springframework.security.oauth2]": DEBUG

