import axios from "axios";
import type { AxiosError } from "axios";
import {
  Permission,
  PermissionResponse,
  PermissionsResponse,
  ApiError,
} from "../type/types";
const API_BASE_URI = import.meta.env.VITE_API_BASE_URI;

// Axios instance with default headers
const apiClient = axios.create({
  baseURL: API_BASE_URI,
  headers: {
    "Content-Type": "application/json",
  },
  withCredentials: true,
});

export const createPermission = async (
  permissionData: Omit<Permission, "id">, // ID might be generated by server
  token: string
): Promise<PermissionResponse> => {
  try {
    const response = await apiClient.post<PermissionResponse>(
      "/permissions",
      permissionData,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );
    return response.data;
  } catch (error) {
    console.error("Error creating permission:", error);
    throw error as AxiosError<ApiError>;
  }
};

export const getAllPermissions = async (
  token: string
): Promise<PermissionsResponse> => {
  try {
    const response = await apiClient.get<PermissionsResponse>("/permissions", {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    return response.data;
  } catch (error) {
    console.error("Error fetching permissions:", error);
    throw error as AxiosError<ApiError>;
  }
};

export const deletePermission = async (
  permissionId: string, // Assuming permission is an ID
  token: string
): Promise<PermissionResponse> => {
  try {
    const response = await apiClient.delete<PermissionResponse>(
      `/permissions/${permissionId}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );
    return response.data;
  } catch (error) {
    console.error("Error deleting permission:", error);
    throw error as AxiosError<ApiError>;
  }
};

