import apiClient from "./authService";
import { handleServiceError } from "./baseService";
import {
  Permission,
  PermissionResponse,
  PermissionsResponse,
} from "../types/UserTypes";

export const createPermission = async (
  permissionData: Omit<Permission, "id">, // ID might be generated by server
  token: string
): Promise<PermissionResponse> => {
  try {
    const response = await apiClient.post<PermissionResponse>(
      "/permissions",
      permissionData,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );
    return response.data;
  } catch (error) {
    console.error("Error creating permission:", error);
    throw handleServiceError(error);
  }
};

export const getAllPermissions = async (
  token: string
): Promise<PermissionsResponse> => {
  try {
    const response = await apiClient.get<PermissionsResponse>("/permissions", {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    return response.data;
  } catch (error) {
    console.error("Error fetching permissions:", error);
    throw handleServiceError(error);
  }
};

export const deletePermission = async (
  permissionId: string, // Assuming permission is an ID
  token: string
): Promise<PermissionResponse> => {
  try {
    const response = await apiClient.delete<PermissionResponse>(
      `/permissions/${permissionId}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );
    return response.data;
  } catch (error) {
    console.error("Error deleting permission:", error);
    throw handleServiceError(error);
  }
};

