name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "TuPhung_Docs/**"
  # Cho phép chạy workflow thủ công từ tab Actions trên GitHub
  workflow_dispatch:

# Quyền cần thiết để đẩy lên GitHub Pages
permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    # Chuyển sang sử dụng Ubuntu thay vì Windows để tránh các vấn đề với Git
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TuPhung_Docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Đảm bảo lấy toàn bộ lịch sử để tránh lỗi shallow clone
          fetch-depth: 0
          # Đảm bảo có token để có quyền đẩy lên repository
          token: ${{ github.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: TuPhung_Docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      # Thiết lập thông tin Git
      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Triển khai lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: TuPhung_Docs/build # Thư mục chứa các file đã build
          branch: gh-pages # Tên nhánh để triển khai
          clean: true # Xóa các file cũ trước khi triển khai
          token: ${{ github.token }} # Sử dụng token để xác thực
